/**
 * Bundles /public HTML, CSS, and JS into webBundle.js for React Native WebView.
 */
const fs = require("fs");
const path = require("path");

const root = path.join(__dirname, "..");
const pub = path.join(root, "public");

const html = fs.readFileSync(path.join(pub, "index.html"), "utf8");
const css = fs.readFileSync(path.join(pub, "styles.css"), "utf8");
const fieldSchemas = fs.readFileSync(path.join(pub, "fieldSchemas.js"), "utf8");
const phillyLimitsPath = path.join(pub, "philly-city-limits.json");
const phillyLimits = fs.readFileSync(phillyLimitsPath, "utf8");
JSON.parse(phillyLimits);
const localesBundlePath = path.join(pub, "locales-bundle.js");
const localesBundle = fs.existsSync(localesBundlePath)
  ? fs.readFileSync(localesBundlePath, "utf8") + "\n"
  : "";
const js =
  "window.__FLICK_PHILLY_LIMITS__=" +
  phillyLimits +
  ";\n" +
  fieldSchemas +
  "\n" +
  localesBundle +
  fs.readFileSync(path.join(pub, "app.js"), "utf8");

const bundled = html
  .replace(
    '<link rel="stylesheet" href="styles.css" />',
    `<style>${css}</style>`
  )
  .replace('<script src="app.js" defer></script>', `<script>${js}</script>`);

const out = path.join(root, "webBundle.js");
fs.writeFileSync(
  out,
  `/* Auto-generated by scripts/inline-web.js — do not edit */\nexport default ${JSON.stringify(bundled)};\n`,
  "utf8"
);

console.log("Wrote webBundle.js");
